---
title: "Stat 245 -- prac"
author: "Adham Rishmawi"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```



```{r}
data1 <- read.csv("https://sldr.netlify.app/data/asthma.csv")
data1
```


```{r}
Asthmaclr <- lm()
```


```{r}
library(glmmTMB)
ER_nbl <- glmmTMB(ERVisits_Asthma_0_17~ median_income + county,
                data = data1,
                family = nbinom1(link = 'log'))
ER_nb2 <- glmmTMB(ERVisits_Asthma_0_17~ median_income + county,
                data = data1,
                family = nbinom2(link = 'log'))


```


```{r}
AIC(ER_nbl, ER_nb2)
```


```{r}
library (DHARMa)
nb2_sim <- simulateResiduals(ER_nb2)
plotResiduals(nb2_sim)
```
  
  