---
title: "Stat 245 --  R Jump Start"
author: "Adham Rishmawi"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 4
    fig_width: 9
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


## Reading in the Data
Maybe describe what I am going to do...

```{r message=FALSE}
wrdata <- read_csv('https://sldr.netlify.app/data/sustainable-livelihoods.csv', show_col_types = FALSE)

```

```{r}
gf_props(~Age_Group,
         fill = ~Management_Confidence,
         denom = ~x,
         data = wrdata)
```




  