---
title: "Stat 245 -- CI's predictors with link func"
author: "A. Student"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)
require(glmmTMB)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


```{r}
sscrime <- read_csv('https://sldr.netlify.app/data/sscrime.csv') |>
  mutate(Location = fct_relevel(Location, 'City', 'Town', 'Urban Fringe', 'Rural'),
         SecurityCameras = factor(SecurityCameras))
```

```{r}
library(glmmTMB)
theft_nb1 <- glmmTMB(Thefts ~ SecurityCameras + StudentIDBadges + Location + offset(log(NEnrollment)),
                     data = sscrime,
                     family = nbinom1(link = 'log'))
summary(theft_nb1)
```

## Hypothetical Data:
```{r}
hyp_data <- expand.grid(SecurityCameras = 'no',
                        StudentIDBadges = c('yes', 'no'),
                        Location = 'Town',
                        NEnrollment = 1000)
```

## Make predictions on link scale:
```{r}
theft_preds <- predict(theft_nb1, newdata = hyp_data,
                       type = "link",
                       se.fit = TRUE)
glimpse(theft_preds)
```

## Compute CIs on link scale, then inverse link transform:
```{r}
hyp_data <- hyp_data |>
  mutate(pred = exp(theft_preds$fit),
         ci_low = exp(theft_preds$fit - 1.96*theft_preds$se.fit),
         ci_up = exp(theft_preds$fit + 1.96*theft_preds$se.fit))
```

## Draw the Plot:
```{r}
gf_point(pred ~ StudentIDBadges,
         data = hyp_data) |>
  gf_errorbar(ci_low + ci_up ~ StudentIDBadges) |>
  gf_labs(y = 'No. Thefts per 1,000')
```

## Interaction: 
```{r}
int_model <- 
  glmmTMB(Thefts ~ Lockers * SecurityCameras,
          family = nbinom2(link = 'log'),
          data = sscrime)
int_model
```

```{r}
gf_boxplot(Thefts ~ Lockers | LockedGates, data = sscrime) %>%
  gf_jitter(alpha = 0.3, width = 0.2) %>%
  gf_labs(x = '')
```

